package ru.practicum.shareit.item.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;

/*
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(1024) NOT NULL,
  item BIGINT REFERENCES items,
  author BIGINT REFERENCES users,
  CONSTRAINT pk_comments PRIMARY KEY (id)
);

 */
@Entity
@Table(name = "comments", schema = "public")
@Getter
@Setter
@ToString

public class Comment {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @Column
    private String text;
    @Column
    private Integer item;
    @Column
    private Integer author;
    @Column
    private String authorName;
    @Column
    private LocalDateTime created;
}
